export const NEW_SORT_OPTIONS = 'NEW_SORT_OPTIONS';
export const NEW_FILTER_OPTIONS = 'NEW_FILTER_OPTIONS';
export const SEARCH_PARAMS = 'SEARCH_PARAMS';
export const IS_VISIBLE_SEARCHBAR = 'IS_VISIBLE_SEARCHBAR';
export const IS_UNVISIBLE_SEARCHBAR = 'IS_UNVISIBLE_SEARCHBAR';
